<a href="https://colab.research.google.com/github/deeplearningexplore/ImageCaptioning/blob/master/Text_Processing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!git init
!git config --global user.email “rohithkankipati4743@gmail.com”
!git config --global user.name “rohith4743”
!git remote add origin https://rohith4743:m114060670046@github.com/deeplearningexplore/ImageCaptioning.git
!git remote set-url origin https://rohith4743:m114060670046@github.com/deeplearningexplore/ImageCaptioning.git
!git add .
!git commit -m "try2"
!git pull origin master --allow-unrelated-histories

Initialized empty Git repository in /content/.git/
[master (root-commit) 531decb] try2
 20 files changed, 50715 insertions(+)
 create mode 100644 .config/.last_opt_in_prompt.yaml
 create mode 100644 .config/.last_survey_prompt.yaml
 create mode 100644 .config/.last_update_check.json
 create mode 100644 .config/.metricsUUID
 create mode 100644 .config/active_config
 create mode 100644 .config/config_sentinel
 create mode 100644 .config/configurations/config_default
 create mode 100644 .config/gce
 create mode 100644 .config/logs/2020.09.11/16.27.12.370477.log
 create mode 100644 .config/logs/2020.09.11/16.27.31.760204.log
 create mode 100644 .config/logs/2020.09.11/16.27.46.134076.log
 create mode 100644 .config/logs/2020.09.11/16.27.51.969599.log
 create mode 100644 .config/logs/2020.09.11/16.28.07.275269.log
 create mode 100644 .config/logs/2020.09.11/16.28.07.905587.log
 create mode 100755 sample_data/README.md
 create mode 100755 sample_data/anscombe.json
 create mode 100644 sample_

In [21]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import os
%matplotlib inline

import tensorflow as tf
from tensorflow.keras.preprocessing.sequence import pad_sequences

import nltk
nltk.download('punkt')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!


True

In [3]:
train_features_df=pd.read_pickle("./features/train0.pkl")
for i in range(1,6):
  temp=pd.read_pickle("./features/train{}.pkl".format(i))
  train_features_df=train_features_df.append(temp,ignore_index=True)
train_features_df.columns

Index(['image_name', 'out', 'sentences'], dtype='object')

In [4]:

validation_features_df=pd.read_pickle("./features/validation.pkl")

validation_features_df.shape

(5000, 3)

In [5]:
test_features_df=pd.read_pickle("./features/test.pkl")
test_features_df.shape

(5000, 3)

In [6]:
word_count={}
max_len=0
for value in train_features_df["sentences"]:
  desc = nltk.word_tokenize(value)
  max_len=np.max((max_len,len(desc)))
  for word in desc:
    count=word_count.get(word,0)
    word_count[word]=count+1
    
print(len(word_count))
print(max_len)

7588
37


In [7]:
vocab=set()
for key,value in word_count.items():
  if(value>3):
    vocab.add(key)
vocab.add("<<unk>>")
print(len(vocab))
print("endseq" in vocab)

2920
True


In [8]:
word_to_index={}
index_to_word={}

for i,v in enumerate(vocab):
  word_to_index[v]=i+1
  index_to_word[i+1]=v

print(word_to_index)
print(index_to_word)

{'making': 1, 'hammer': 2, 'deer': 3, 'shopping': 4, 'bicycles': 5, 'returns': 6, 'bracelet': 7, 'rocket': 8, 'father': 9, 'rafts': 10, 'sideways': 11, 'perched': 12, 'tent': 13, 'dusk': 14, 'heart': 15, 'around': 16, 'hikers': 17, 'either': 18, 'basketball': 19, 'skateboarders': 20, 'item': 21, 'grassy': 22, 'hilly': 23, 'canal': 24, 'melting': 25, 'skinned': 26, 'magazine': 27, 'grey': 28, 'bark': 29, 'bandanna': 30, 'trotting': 31, 'smiling': 32, 'posing': 33, 'jeeps': 34, 'cardboard': 35, 'trots': 36, 'wire': 37, 'treelined': 38, 'rests': 39, 'foot': 40, 'park': 41, 'suit': 42, 'breed': 43, 'rest': 44, 'electronic': 45, 'chatting': 46, 'awards': 47, 'bedspread': 48, 'lined': 49, 'hoop': 50, 'racers': 51, 'lab': 52, 'markings': 53, 'swampy': 54, 'chalk': 55, 'stops': 56, 'drenched': 57, 'taken': 58, 'beak': 59, 'selling': 60, 'fellow': 61, 'icicle': 62, 'silhouette': 63, 'leggings': 64, 'mess': 65, 'photograph': 66, 'teams': 67, 'hardhat': 68, 'masks': 69, 'superman': 70, 'bowling':

In [9]:
def indexing(sentence):
  emp=[]
  desc = nltk.word_tokenize(sentence)
  for word in desc:
    if(word in vocab):
      emp.append(word_to_index[word])
    else:
      emp.append(word_to_index["<<unk>>"])
  return emp


train_features_df["indexed"]=train_features_df["sentences"].apply(indexing)
train_features_df.iloc[0]["indexed"]

[911,
 1370,
 1426,
 1987,
 1663,
 2499,
 1585,
 1370,
 263,
 1987,
 2751,
 1056,
 585,
 2141]

In [10]:
temp=train_features_df.iloc[:2]["indexed"]
temp




0    [911, 1370, 1426, 1987, 1663, 2499, 1585, 1370...
1    [911, 1426, 1987, 1769, 1069, 1987, 895, 585, ...
Name: indexed, dtype: object

In [12]:
def padding(indexes,features):
  sequences_x=[]
  y=[]
  fat=[]
  for k,seq in enumerate(indexes):
    for i in range(1,len(seq)):
      x=seq[:i]
      sequences_x.append(x)
      y.append(seq[i])
      fat.append(features[k])
  
  x=pad_sequences(sequences_x,value=0,padding='pre',maxlen=37)
  y=np.array(y)
  y=np.expand_dims(y,axis=-1)
  return (np.array(x),y,np.array(fat))


train_x,train_y,train_features_x=padding(train_features_df["indexed"],train_features_df["out"])
print(train_x.shape)
print(train_y.shape)
print(train_features_x.shape)



(353506, 37)
(353506, 1)
(353506, 2048)


In [13]:
validation_features_df["indexed"]=validation_features_df["sentences"].apply(indexing)
valid_x,valid_y,valid_features_x=padding(validation_features_df["indexed"],validation_features_df["out"])

print(valid_x.shape)
print(valid_y.shape)
print(valid_features_x.shape)

(59493, 37)
(59493, 1)
(59493, 2048)


In [16]:
train_x[0], train_y[0], train_features_x[0]

(array([  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0, 911], dtype=int32),
 array([1370]),
 array([0.00124186, 0.39404634, 0.        , ..., 0.26349303, 0.00386622,
        0.10866498], dtype=float32))

In [17]:
test_features_df["indexed"]=test_features_df["sentences"].apply(indexing)


In [18]:
#*************************GLOVE EMBEDDINGS TO VOCAB EMBEDDINGS************************
# !wget http://nlp.stanford.edu/data/glove.6B.zip


# import zipfile
# zip_ref = zipfile.ZipFile("glove.6B.zip", 'r')
# zip_ref.extractall("./glove/")
# zip_ref.close()


# embeddings_index = {}
# f = open(os.path.join("glove", 'glove.6B.200d.txt'))
# for line in f:
#     values = line.split()
#     word = values[0]
#     coefs = np.asarray(values[1:], dtype='float32')
#     embeddings_index[word] = coefs
# f.close()

# e_dim = 200
# embedding_matrix = np.zeros((len(vocab)+1, e_dim))
# for word, i in word_to_index.items():
#     embedding_vector = embeddings_index.get(word)
#     if embedding_vector is not None:
#         # words not found in embedding index will be all-zeros.
#         embedding_matrix[i] = embedding_vector
# np.save("embeddings",embedding_matrix)

--2020-09-15 07:10:51--  http://nlp.stanford.edu/data/glove.6B.zip
Resolving nlp.stanford.edu (nlp.stanford.edu)... 171.64.67.140
Connecting to nlp.stanford.edu (nlp.stanford.edu)|171.64.67.140|:80... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://nlp.stanford.edu/data/glove.6B.zip [following]
--2020-09-15 07:10:51--  https://nlp.stanford.edu/data/glove.6B.zip
Connecting to nlp.stanford.edu (nlp.stanford.edu)|171.64.67.140|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: http://downloads.cs.stanford.edu/nlp/data/glove.6B.zip [following]
--2020-09-15 07:10:51--  http://downloads.cs.stanford.edu/nlp/data/glove.6B.zip
Resolving downloads.cs.stanford.edu (downloads.cs.stanford.edu)... 171.64.64.22
Connecting to downloads.cs.stanford.edu (downloads.cs.stanford.edu)|171.64.64.22|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 862182613 (822M) [application/zip]
Saving to: ‘glove.6B.zip’

glove.6

In [31]:
embedding_matrix = np.load("embeddings.npy")
embedding_matrix.shape

(2921, 200)

array([ 1.01580001e-01,  3.78039986e-01, -5.18719971e-01, -1.45290002e-01,
       -5.09289987e-02,  7.04680011e-02, -4.05519992e-01, -4.77030016e-02,
        7.66260028e-02,  6.07779995e-02, -2.16800004e-01,  4.81169999e-01,
       -4.89560008e-01,  1.13370001e-01,  3.77409995e-01,  4.36250001e-01,
       -1.98420003e-01,  2.95089990e-01,  4.41339999e-01, -5.11900000e-02,
        1.24779999e-01,  2.86910009e+00, -3.70269991e-03, -5.86999990e-02,
       -1.88920006e-01,  3.47350001e-01, -7.13289995e-03,  2.65570004e-02,
        2.10329995e-01, -2.44169995e-01,  5.54549992e-02,  2.62790006e-02,
        1.43020004e-01,  3.97260010e-01, -1.06430002e-01, -7.97310024e-02,
       -5.87509990e-01, -4.38890010e-01, -5.92770018e-02,  4.37159985e-01,
       -9.50549990e-02, -2.16470003e-01,  4.94969994e-01,  7.87710026e-02,
        2.45020002e-01,  1.44470006e-01,  9.16339979e-02,  1.63819999e-01,
       -4.06010002e-01,  2.29259998e-01, -1.10179998e-01, -1.74119994e-01,
        1.06899999e-01,  